instance:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'localhost'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:10080'
  ports:
    - '80:10080'
    - '443:443'
    - '10022:10022'
  volumes:
    - '/Users/moises/docker/gitlab/config:/etc/gitlab'
    - '/Users/moises/docker/gitlab/logs:/var/log/gitlab'
    - '/Users/moises/docker/gitlab/data:/var/opt/gitlab'
